### your site title here

title: Your Site Title



collections:
        products:
            output: true
            permalink: /products/:path/


### exclude the instructions / write-up in the README.md

exclude:
- README.md


plugins:
    - jekyll-seo-tag